name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Build the React application
        run: npm run build

      - name: Authenticate with Firebase
        run: |
          echo "$FIREBASE_TOKEN" | firebase login --no-interactive
          firebase use --token "$FIREBASE_TOKEN" --add

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting